# Part 2

##### Goal: Do imputation and Label Coding

In [4]:
import pandas as pd
#code to import .dat file

#path of my file
p= "D:\\CIC\\CIP\\Tareas\\Tarea_12\\housevotes.dat"

df = []

with open(p, 'r') as file:
    for line in file:
        if line.startswith('@'):
            # skip comment lines
            continue
        row = line.strip().split(',')
        df.append(row)

df=pd.DataFrame(df)

In [21]:
df

    0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15          16
0    n  y  n  y  y  y  n  n  n  y  ?  y  y  y  n  y  republican
1    n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  ?  republican
2    ?  y  y  ?  y  y  n  n  n  n  y  n  y  y  n  n    democrat
3    n  y  y  n  ?  y  n  n  n  n  y  n  y  n  n  y    democrat
4    y  y  y  n  y  y  n  n  n  n  y  ?  y  y  y  y    democrat
..  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..         ...
430  n  n  y  y  y  y  n  n  y  y  n  y  y  y  n  y  republican
431  n  n  y  n  n  n  y  y  y  y  n  n  n  n  n  y    democrat
432  n  ?  n  y  y  y  n  n  n  n  y  y  y  y  n  y  republican
433  n  n  n  y  y  y  ?  ?  ?  ?  n  y  y  y  n  y  republican
434  n  y  n  y  y  y  n  n  n  y  n  y  y  y  ?  n  republican

[435 rows x 17 columns]

In [23]:
#shape give to me a tuple (rows,columns) 
num_col= df.shape[1] 
num_rows= df.shape[0]
print(num_rows)

435

#### Part 1: do Imputation of the missing values. It will be used the column mode to change a missing value '?'

In [27]:
#Imputation
import statistics

for col in range(num_col-1):
    
    mode = statistics.mode(df[col])
    
    for row in range(num_rows):
        if df[col][row]=='?':
            df[col][row]=mode

In [28]:
df

    0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15          16
0    n  y  n  y  y  y  n  n  n  y  n  y  y  y  n  y  republican
1    n  y  n  y  y  y  n  n  n  n  n  y  y  y  n  y  republican
2    n  y  y  n  y  y  n  n  n  n  y  n  y  y  n  n    democrat
3    n  y  y  n  y  y  n  n  n  n  y  n  y  n  n  y    democrat
4    y  y  y  n  y  y  n  n  n  n  y  n  y  y  y  y    democrat
..  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..         ...
430  n  n  y  y  y  y  n  n  y  y  n  y  y  y  n  y  republican
431  n  n  y  n  n  n  y  y  y  y  n  n  n  n  n  y    democrat
432  n  y  n  y  y  y  n  n  n  n  y  y  y  y  n  y  republican
433  n  n  n  y  y  y  y  y  y  y  n  y  y  y  n  y  republican
434  n  y  n  y  y  y  n  n  n  y  n  y  y  y  n  n  republican

[435 rows x 17 columns]

#### Part 2: Do Label coding. Change "y" to 1 and "n" to 2

In [29]:
#label Coding 
for col in range(num_col-1):
    
    for row in range(num_rows):
        if df[col][row]=='y':
            df[col][row]=1
        else:
            df[col][row]=2

In [30]:
df

    0  1  2  3  4  5  6  7  8  9  10 11 12 13 14 15          16
0    2  1  2  1  1  1  2  2  2  1  2  1  1  1  2  1  republican
1    2  1  2  1  1  1  2  2  2  2  2  1  1  1  2  1  republican
2    2  1  1  2  1  1  2  2  2  2  1  2  1  1  2  2    democrat
3    2  1  1  2  1  1  2  2  2  2  1  2  1  2  2  1    democrat
4    1  1  1  2  1  1  2  2  2  2  1  2  1  1  1  1    democrat
..  .. .. .. .. .. .. .. .. .. .. .. .. .. .. .. ..         ...
430  2  2  1  1  1  1  2  2  1  1  2  1  1  1  2  1  republican
431  2  2  1  2  2  2  1  1  1  1  2  2  2  2  2  1    democrat
432  2  1  2  1  1  1  2  2  2  2  1  1  1  1  2  1  republican
433  2  2  2  1  1  1  1  1  1  1  2  1  1  1  2  1  republican
434  2  1  2  1  1  1  2  2  2  1  2  1  1  1  2  2  republican

[435 rows x 17 columns]

In [65]:
df_lst = df.values.tolist()
#print(df_lst)

In [66]:
def balanced_df(df,class_1,class_2):
    n= len(df[0])-1 #suppose the class column is the last element in the vector
    
    counter_1 = 0
    counter_2 = 0
    
    for x in df:
        if x[n] == class_1:
            counter_1 += 1
        else:
            counter_2 += 1
    
    if max(counter_1,counter_2)/min(counter_1,counter_2)>1.5:
        print(f'Desbalanced Data Set: {max(counter_1,counter_2)}/{min(counter_1,counter_2)}={max(counter_1,counter_2)/min(counter_1,counter_2)}')
        if max(counter_1,counter_2)==counter_1:
            print(f"The bigger class is the: {class_1}")
        else:
            print(f"The bigger class is the: {class_2}")
    else:
        print(f'Balanced Data Set: {max(counter_1,counter_2)}/{min(counter_1,counter_2)}={max(counter_1,counter_2)/min(counter_1,counter_2)}')
        if max(counter_1,counter_2)==counter_1:
            print(f"The bigger class is the: {class_1}")
        else:
            print(f"The bigger class is the: {class_2}")

In [67]:
balanced_df(df_lst,"republican","democrat")

Desbalanced Data Set: 267/168=1.5892857142857142
The bigger class is the: democrat

#### I will re-order the dataset such that all the first patterns are from positive class and the secon part should be from the negative class

In [34]:
def pos_and_neg(df,class_pos,class_neg):
    n = len(df[0])-1 #position of the class column
    
    df_pos = []
    df_neg = []
    
    for x in df:
        if x[n] == class_pos:
            df_pos.append(x)
        else:
            df_neg.append(x)
    
    for row in df_pos: #remove the class column
        row.pop()
    
    for row in df_neg: #remove the class column
        row.pop()
    
    return df_pos,df_neg

### We will take: positive as republican and negative as democrat

In [54]:
class_pos='republican'
class_neg="democrat"

df_pos,df_neg = pos_and_neg(df_lst,class_pos,class_neg)

In [60]:
data = df_pos + df_neg
#print(data)

In [61]:
last_pos_index=len(df_pos)-1

### Let's move on to the 1-NN classifier

In [62]:
from collections import Counter
import math
from tabulate import tabulate

#K-NN with Leave One Out Cross Validation

#value of minkowski_value it's just needed if i will use one of those metrics if i will not use them, then i can delete that parameter
#by commenting also the distance line 
def knn_LOOCV(k,df_validation,class_positive,class_negative,index_test,last_positive_index,TP,FN,FP,TN):
    
    train_df = df_validation #dataset where the first patterns are all positive class and the second part are all negative class

    pattern_index = index_test
    test_df = df_validation[pattern_index]

    n=last_positive_index
    
    if pattern_index<=n:
        class_of_test_pattern = class_positive
    else:
        class_of_test_pattern = class_negative

    distances = []

    for i in range(len(train_df)):
        
        #the lines below correspond to different distances 
        
        dist = round(math.dist(test_df, train_df[i]),4) #Euclidian metric
        #dist = round(mink_metric(minkowski_value,test_df,train_df[i]),4) #minkowski metric
        #dist = round(chebyshev_metric(test_df,train_df[i]),4) #Chebyshev metric

        if i<=n:
            distances.append([dist,i+1,class_positive]) #it need to be sum one because of the python numeration
        else:
            distances.append([dist,i+1,class_negative])

    del distances[pattern_index] #delete the list of distance from the test pattern to itself       

    kNN=k
    sorted_dist = sorted(distances, key=lambda x: x[0])[:kNN]
    #print(sorted_dist)
    #create the table of the top 3 min sorted distances

    # create the table headers
    #headers = ['Distancia', 'PatrÃ³n', 'Clase del patrÃ³n']

    #table_latex = tabulate(sorted_dist, headers,floatfmt=".4f", tablefmt='latex')

    # print(f"\n\item PatrÃ³n {pattern_index+1}. Ver tabla \\ref{{fig{pattern_index+1}}} \n")
    # print("\\begin{table}")
    # print("\centering")
    # print(table_latex)
    # print(f"\caption{{Tabla para el patrÃ³n {pattern_index+1} (NUTT Dataset)}}")
    # print(f"\label{{fig{pattern_index+1}}}")
    # print("\\end{table}")


    #now i want to count the most repeated class from the KNN list

    # extract the third element from each sublist and put them in a separate list
    third_elements = [sublist[2] for sublist in sorted_dist]

    # use Counter to count the frequency of each value in the third_elements list
    counter = Counter(third_elements)

    most_common_class = counter.most_common(1)[0][0] #this print the most common class

    #print(f"\nLa clase que le asgina el clasificador: {most_common_class}")
    
    if most_common_class == class_of_test_pattern:
        
        #print("\nFue un \\textbf{ACIERTO}")
        
        if class_of_test_pattern==class_positive:
            TP +=1
        elif class_of_test_pattern==class_negative:
            TN +=1
    else:
        #print("\nFue un \\textbf{ERROR}")

        if class_of_test_pattern==class_positive:
            FN +=1
        elif class_of_test_pattern==class_negative:
            FP +=1
    return TP,FN,FP,TN

In [63]:
class_positive='republican'
class_negative="democrat"

n=last_pos_index

TP=0
FN=0
FP=0
TN=0

for i in range(len(data)):
    TP,FN,FP,TN=knn_LOOCV(1,data,class_positive,class_negative,i,n,TP,FN,FP,TN)

    
CM=[[TP,FN],[FP,TN]]
print(CM)

[[161, 7], [35, 232]]

In [74]:
def precision(CM):
    TP = CM[0][0]
    FN = CM[0][1]
    
    FP = CM[1][0]
    TN = CM[1][1] 
    
    preci = TP/(TP+FP)
    
    return preci

def f1(CM):
    TP = CM[0][0]
    FN = CM[0][1]
    
    FP = CM[1][0]
    TN = CM[1][1] 
    
    f1 = (2*TP)/(2*TP+FN+FP)
    
    return f1
    
def mcc(CM):
    TP = CM[0][0]
    FN = CM[0][1]
    
    FP = CM[1][0]
    TN = CM[1][1] 
    
    mcc = (TP*FP-FP*FN)/((TP+FP)*(TP+FN)*(TN+FP)*(TN+FN))
    
    return mcc
    

def medidas(CM):
    accuracy = round((CM[0][0]+CM[1][1])/(sum(CM[0])+sum(CM[1])),4)
    recall = round((CM[0][0]) / (sum(CM[0])),4)
    specificity = round((CM[1][1])/sum(CM[1]),4)
    balanced_acc= round((recall+specificity)/2,4)
    # precision = precision(CM)
    # f1 = f1(CM)
    # mcc = mcc(CM) 
    
    print(f"-Accuracy:{accuracy}\n-Recall:{recall}\n-Specificity: {specificity}\n-Balanced Accuracy:{balanced_acc}\n-Precision: {precision}\n-f1: {f1}\n-MCC: {mcc}")

In [75]:
medidas(CM)

-Accuracy:0.9034
-Recall:0.9583
-Specificity: 0.8689
-Balanced Accuracy:0.9136
-Precision: <function precision at 0x000001E74D563B80>
-f1: <function f1 at 0x000001E74C2A4310>
-MCC: <function mcc at 0x000001E74C2A40D0>