In [1]:
import pandas as pd
import numpy as np
import math

In [10]:
#funcion para hacer hold out
def hold_out(df,clase_1,clase_2,porcentaje):
    #generar los respectivos datasets de las clases

    #df.iloc[row_start:row_end , col_start, col_end]

    c0 = df[df.iloc[: , -1] == clase_1] #si la ultima columna es igual a 0

    c1 = df[df.iloc[: , -1] == clase_2] #si la ultima columna es igual a 1
    
    
    #drop class column for both datasets
    c0=c0.drop(c0.columns[-1],axis=1) #drop la ultima columna, axis=1 significa que la buscara en columnas, axis=0 lo busca en rows

    c1=c1.drop(c1.columns[-1],axis=1)
    
        #permutation over the ci indexes
    c0=c0.reindex(np.random.permutation(c0.index))
    c1=c1.reindex(np.random.permutation(c1.index))
    
    #estamos trabajando con un hold out 80-20 ent
    a = porcentaje/100
    
    h80_0= int(math.floor(len(c0)*a)) # 80% de la clase 0

    h20_0= len(c0)-h80_0 # 20% de la clase 0

    h80_1= int(math.floor(len(c1)*a)) # 80% de la clase 0

    h20_1= len(c1)-h80_0 # 20% de la clase 0
    
    #conjunto de entrenamiento
    #desde la fila 0 hasta la (h80_0)-1 (total h80_0 filas)
    E0 = c0.iloc[:h80_0] #entrenamiento clase 0

    #conjunto de prueba
    #desde la fila h80_0 hasta la ultima
    P0 = c0.iloc[h80_0:len(c0)+1] #prueba clase 0

    #Lo mismo para la clase 1

    E1 = c1.iloc[:h80_1] #entrenamiento clase 1
    P1 = c1.iloc[h80_1:len(c1)+1] #prueba clase 0 
    
    
    return E0,P0,E1,P1

In [4]:
p1="D:\\CIC\\CIP\\data_sets\\Haberman\\a√±os\\haberman_58.csv"

In [9]:
df = pd.read_csv(p1,delimiter=";", decimal=",",header=None)
df

     0   1  2
0   33  10  1
1   34  30  1
2   37   0  1
3   39   0  1
4   40   2  1
5   40   0  1
6   41   0  1
7   42   0  1
8   46   3  1
9   47   3  1
10  50   1  1
11  53   1  1
12  54   1  1
13  55   0  1
14  55   1  1
15  58   0  1
16  58   3  1
17  64   0  1
18  66   1  1
19  72   0  1
20  43  52  2
21  44   9  2
22  46   2  2
23  48  11  2
24  53   4  2
25  70   0  2
26  70   4  2
27  83   2  2

In [17]:
E1,P1,E2,P2 = hold_out(df,1,2,80)

In [29]:
index_list_E1 = E1.index.values.tolist()

index_list_E2 = E2.index.values.tolist()

In [30]:
index_list_E1

[18, 0, 14, 5, 12, 4, 7, 13, 19, 8, 17, 10, 9, 3, 11, 15]

In [31]:
index_list_E2

[25, 21, 26, 24, 22, 23]

### Clasificador Euclidiano

In [36]:
def centroide(df):
    centroi = df.mean(axis=0).tolist()
    return centroi

import math
def clasificador(point,c1,c2,clase_original,n_pattern):
    line = "\n"
    
    
    print(f" \item El patr√≥n #{n_pattern} del conjunto de prueba que pertenece a la clase {clase_original}: {line}")
    
    dist_c1 = round(math.dist(point, c1),2)
    print(f"La distancia con el centroide 0 es: {dist_c1} {line} ")
    
    dist_c2= round(math.dist(point, c2),2)
    print(f"La distancia con el centroide 1 es: {dist_c2} {line}")
    
    dist_min = min (dist_c1,dist_c2)
    
    if dist_min == dist_c1:
        print(f"El punto est√° m√°s cerca del centroide 0. {line}")
        
        if clase_original == 0:
            print(f"La clasificaci√≥n fue correcta. {line} \n")
        else:
            print(f"La clasificaci√≥n fue INCORRECTA.{line} \n")
    else:
        print(f"El punto est√° m√°s cerca del centroide 1.{line}")
        
        if clase_original == 1:
            print(f"La clasificaci√≥n fue correcta.{line} \n")
        else:
            print(f"La clasificaci√≥n fue INCORRECTA. {line} \n")

In [18]:
centroide1= centroide(E1)
centroide2= centroide(E2)

In [32]:
#convertir datasets de prueba en listas 2D para poder sacar distancias

lista_P1 = P1.values.tolist() #cada row es una lista aqui

lista_P2 = P2.values.tolist()

In [37]:
n=1
for x in lista_P1:
    clasificador(x,centroide1,centroide2,1,n)
    n +=1

 \item El patr√≥n #1 del conjunto de prueba que pertenece a la clase 1:

La distancia con el centroide 0 es: 7.29

La distancia con el centroide 1 es: 3.47

El punto est√° m√°s cerca del centroide 1.

La clasificaci√≥n fue correcta.


 \item El patr√≥n #2 del conjunto de prueba que pertenece a la clase 1:

La distancia con el centroide 0 es: 9.98

La distancia con el centroide 1 es: 15.02

El punto est√° m√°s cerca del centroide 0.

La clasificaci√≥n fue INCORRECTA.


 \item El patr√≥n #3 del conjunto de prueba que pertenece a la clase 1:

La distancia con el centroide 0 es: 33.18

La distancia con el centroide 1 es: 32.76

El punto est√° m√°s cerca del centroide 1.

La clasificaci√≥n fue correcta.


 \item El patr√≥n #4 del conjunto de prueba que pertenece a la clase 1:

La distancia con el centroide 0 es: 13.95

La distancia con el centroide 1 es: 18.84

El punto est√° m√°s cerca del centroide 0.

La clasificaci√≥n fue INCORRECTA.

In [38]:
for x in lista_P2:
    clasificador(x,centroide1,centroide2,2,n)
    n +=1

 \item El patr√≥n #5 del conjunto de prueba que pertenece a la clase 2:

La distancia con el centroide 0 es: 51.17

La distancia con el centroide 1 es: 48.55

El punto est√° m√°s cerca del centroide 1.

La clasificaci√≥n fue INCORRECTA.


 \item El patr√≥n #6 del conjunto de prueba que pertenece a la clase 2:

La distancia con el centroide 0 es: 32.13

La distancia con el centroide 1 es: 27.99

El punto est√° m√°s cerca del centroide 1.

La clasificaci√≥n fue INCORRECTA.